# Generated by Django 5.1.7 on 2025-03-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='aktiv',
            field=models.BooleanField(default=True),
        ),
    ]
